services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.6

    entrypoint: /bin/bash
    command:
      - -cxe
      - |
        /opt/keycloak/bin/kc.sh import --verbose --file=/input/testdata/keycloak-realm.json
        /opt/keycloak/bin/kc.sh start

    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_HOSTNAME=keycloak.127.0.0.1.nip.io
      - KC_PROXY_HEADERS=xforwarded
      - KC_HTTP_ENABLED=true

    volumes:
      - '.:/input:ro'

    ports:
      - '10443:8443'

  envoy:
    image: envoyproxy/envoy:v1.31-latest
    command: --log-level info --config-path /input/testdata/envoy/envoy-config.yaml
    ports:
      - '127.0.0.1:443:8080'
    user: '1000:1000'
    volumes:
      - '.:/input:ro'
      - '/tmp/:/tmp/'
    extra_hosts:
      - "host.docker.internal:host-gateway"
